# Generated by Django 4.0.2 on 2022-02-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('listing_type', models.CharField(choices=[('C', 'Cloth'), ('M', 'Music'), ('B', 'Book'), ('O', 'Other')], max_length=1)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bands.band')),
            ],
        ),
    ]
